---

- hosts: all
  tasks:
    - name: "Configure CDH5 YUM repository"
      yum_repository:
        name: "cloudera-cdh5"
        description: "Cloudera's distribution for Hadoop, Version 5"
        baseurl: "https://archive.cloudera.com/cdh5/redhat/6/x86_64/cdh/5.3.8/"
        gpgkey: "http://archive.cloudera.com/cdh5/redhat/6/x86_64/cdh/RPM-GPG-KEY-cloudera"
        gpgcheck: yes
