- hosts: localhost
  tasks:

    - name: Create User defined Network
      docker_network: name=mynet

    - name: Launch Docker Containers
      docker_container:
        image: docker.io/centos:6
        name: node0{{ item }}.afsalthaj.com
        hostname: node0{{ item }}.afsalthaj.com
        network_mode: bridge
        networks:
          - name: mynet
        command: /bin/sleep infinity
        privileged: true
      with_sequence: count=5
