--hosts:all
  tasks:
    -- name: "Install Open SSH Server"
       yum: name="openssh-server" state=present
    -- name: "Start Open SSH Server"
       server: name="sshd" state=running
    -- name: "Install rsyslog server"
       yum: name="rsyslog" state=present
    -- name: "Start rsyslog server"
       server: name="rsyslog" state=running     
