---

- hosts: resourcemanager
  tasks:
    - name: Install Hadoop Yarn ResourceManager
      yum:
        name: hadoop-yarn-resourcemanager
        state: present

- hosts: nodemanager
  tasks:
    - name: Install Hadoop Yarn NodeManager
      yum:
        name: hadoop-yarn-nodemanager
        state: present

- hosts: proxyserver
  tasks:
    - name: Install Hadoop Yarn ProxyServer
      yum:
        name: hadoop-yarn-proxyserver
        state: present

- hosts: resourcemanager, nodemanager, proxyserver
  vars:
    yarn_site:
      yarn.nodemanager.aux-services: "mapreduce_shuffle"
      yarn.resourcemanager.hostname: "{{ hostvars['node01.afsalthaj.com']['ansible_eth1']['ipv4']['address'] }}"
      yarn.resourcemanager.bind-host: "0.0.0.0"
      yarn.resourcemanager.admin.address: "{{ hostvars['node01.afsalthaj.com']['ansible_eth1']['ipv4']['address'] }}:8033"
      yarn.resourcemanager.address: "{{ hostvars['node01.afsalthaj.com']['ansible_eth1']['ipv4']['address'] }}:8032"
      yarn.resourcemanager.scheduler.address: "{{ hostvars['node01.afsalthaj.com']['ansible_eth1']['ipv4']['address'] }}:8030"
      yarn.resourcemanager.resource-tracker.address: "{{ hostvars['node01.afsalthaj.com']['ansible_eth1']['ipv4']['address'] }}:8031"
      yarn.application.classpath: "$HADOOP_CONF_DIR, $HADOOP_COMMON_HOME/*, $HADOOP_COMMON_HOME/lib/*, $HADOOP_HDFS_HOME/*, $HADOOP_HDFS_HOME/lib/*, $HADOOP_MAPRED_HOME/*, $HADOOP_MAPRED_HOME/lib/*, $HADOOP_YARN_HOME/*, $HADOOP_YARN_HOME/lib/*"
      yarn.web-proxy.address: "{{ hostvars['node02.afsalthaj.com']['ansible_eth1']['ipv4']['address'] }}:43695"
      yarn.log-aggregation-enable: true
      yarn.log-aggregation.retain-seconds: "259200"

    mapred_site:
      mapreduce.framework.name: yarn

  tasks:
    - name: Configure mapred-site.xml
      template:
        src: mapred-site.xml.j2
        dest: /etc/hadoop/conf/mapred-site.xml
      when: mapred_site is defined
      notify:
        - Restart Hadoop Yarn NodeManager
        - Restart Hadoop Yarn ResourceManager
        - Restart Hadoop Yarn ProxyServer

    - name: Configure yarn-site.xml
      template:
        src: yarn-site.xml.j2
        dest: /etc/hadoop/conf/yarn-site.xml
      when: yarn_site is defined
      notify:
        - Restart Hadoop Yarn NodeManager
        - Restart Hadoop Yarn ResourceManager
        - Restart Hadoop Yarn ProxyServer

  handlers:
    - name: Restart Hadoop Yarn ResourceManager
      service:
        name: hadoop-yarn-resourcemanager
        state: restarted
      when: "'resourcemanager' in group_names"

    - name: Restart Hadoop Yarn NodeManager
      service:
        name: hadoop-yarn-nodemanager
        state: restarted
      when: "'nodemanager' in group_names"

    - name: Restart Hadoop Yarn ProxyServer
      service:
        name: hadoop-yarn-proxyserver
        state: restarted
      when: "'proxyserver' in group_names"

- hosts: resourcemanager
  tasks:
    - name: Start Hadoop Yarn ResourceManager
      service:
        name: hadoop-yarn-resourcemanager
        state: started

- hosts: nodemanager
  tasks:
    - name: Start Hadoop Yarn NodeManager
      service:
        name: hadoop-yarn-nodemanager
        state: started

- hosts: proxyserver
  tasks:
    - name: Start Hadoop Yarn ProxyServer
      service:
        name: hadoop-yarn-proxyserver
        state: started
